# --------------------------
# Stage 1: Development
# --------------------------
    FROM node:18 AS dev

    WORKDIR /app
    
    COPY package*.json ./
    RUN npm install
    
    COPY . .
    
    EXPOSE 3000
    
    CMD ["npm", "run", "dev"]
    
    # --------------------------
    # Stage 2: Production
    # --------------------------
    FROM node:18 AS build
    
    WORKDIR /app
    
    COPY package*.json ./
    RUN npm install
    
    COPY . .
    RUN npm run build
    
    # Final stage: clean production image
    FROM node:18 AS prod
    
    WORKDIR /app
    
    COPY package*.json ./
    RUN npm install --omit=dev
    
    COPY --from=build /app/dist ./dist
    COPY .env .env
    
    EXPOSE 3000
    
    CMD ["node", "dist/index.js"]